version: '3.8'

services: 
    app:
        container_name: opinion-ate
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - "3000:3000"
        volumes: 
            - .:/app
            - /app/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: npm start
        stdin_open: true
        tty: true