version: '3.8'

services: 
    app:
        container_name: opinion-ate
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - "3000:3000"
        volumes: 
            - .:/app
            - /app/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: npm start
        stdin_open: true
        tty: true

    cypress:
        container_name: cypress
        depends_on: 
            - app
        image: cypress/included:4.4.0
        command: cypress run
        volumes: 
            - ./:/e2e
        working_dir: /e2e
        environment:
            - CYPRESS_baseUrl=http://app:3000